openapi: 3.0.0
info:
  title: "Flask REST API"
  description: "API to summarize news articles using an LLM"
  version: "1.0.0"

servers:
  - url: "/api"

components:
  schemas:
    Url:
      type: "object"
      required:
        - url
      properties:
        url:
          type: "string"

paths:
  /categories:
    get:
      operationId: "service.summarizer_service.get_available_categories"
      tags:
        - "News"
      summary: "Read the list of list of available news categories"
      responses:
        "200":
          description: "Successfully read list of available categories"

  /category_headlines_summaries:
    get:
      operationId: "service.summarizer_service.category_headlines_summaries"
      parameters:
        - in: query
          name: category
          required: true
          schema:
            type: string
          description: The category of articles to retrieve
      tags:
        - "News"
      summary: "Get the summaries of the top 3 headlines on the selected category page of the BBC website"
      responses:
        "200":
          description: "Successfully read news categories list"

  /article_summary:
    post:
      operationId: "service.summarizer_service.submit_free_url"
      tags:
        - "News"
      summary: "Get summary of a single BBC article via uploading its link"
      requestBody:
          description: "Article to summarize"
          required: True
          content:
            application/json:
              schema:
                x-body-name: "url"
                $ref: "#/components/schemas/Url"
      responses:
        "201":
          description: "Successfully generated summary"

