openapi: 3.0.0
info:
  title: "Flask REST API"
  description: "API to summarize news articles using an LLM"
  version: "1.0.0"

servers:
  - url: "/api"

components:
  schemas:
    Prompt:
      type: "object"
      required:
        - text
      properties:
        text:
          type: "string"

paths:
  /news:
    get:
      operationId: "service.summarizer_service.test"
      tags:
        - "News"
      summary: "Read the list of news categories"
      responses:
        "200":
          description: "Successfully read news categories list"
  /summary:
    post:
      operationId: "service.summarizer_service.get_summary"
      tags:
        - "News"
      summary: "Get summary"
      requestBody:
          description: "Article to summarize"
          required: True
          content:
            application/json:
              schema:
                x-body-name: "prompt"
                $ref: "#/components/schemas/Prompt"
      responses:
        "201":
          description: "Successfully generated summary"

